name: Build Flet APK
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup uv
        uses: astral-sh/setup-uv@v6

      - name: Build APK
        shell: bash
        run: |
          pip install flet
          flet build apk --yes --verbose

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: apk-build
          path: build/apk/app-release.apk
          
      - name: Build APK
        run: |
          pip install flet
          flet build apk --yes --verbose
          
      - name: Listar arquivos gerados
        run: ls -R build
